### ISSUE TITLE
Issue when using 2 hosts

### ISSUE THREAD

**Issue by gluplu** [wd/fluent-plugin-flume-thrift#1]
Hello,

First of all a big thanks for the plugin that is compatible with newer versions of flume! 
I have run into the following issue when declaring two flume hosts in the config. It seems that only the first host is used. If I bring down the first declared host, fluentd will complain about it being down, but never resort to the second host, ultimately dropping the log messages when in reaches its retry_limit. If the second host is brought down, the fluentd daemon never notices.

**Comment by wd** [comment]
It's been a long time I've write this plugin. I've read the code again, when sending a message, this plugin will loop all the nodes, if one node failed, it will reconnect this node, and try send to the next node. There is currently no balance method between nodes, it's should be have though...

```
      @nodes.each do |node|
        begin
          send_data(node.client, chunk)
          return
        rescue
          error = $!
          $log.error "Got error for node '#{node.name}': #{error}, try reconnect"
          node.connect()
        end
      end
```

**Comment by gluplu** [comment]
It actually gets stuck on the first node. I added a line $log.info "Trying to send through '#{node.host}'" just before send_data and it never gets to the second node. Here is the relevant log from fluentd, it includes my conf as well:

`2015-11-24 23:51:48 -0500 [info]: using configuration file: <ROOT>
  <match debug.**>
    type stdout
  </match>
  <match *.*>
    type flume
    max_retry_wait 20
    retry_limit 3
    <server>
      host 10.149.1.62
      port 4141
    </server>
    <server>
      host 10.149.12.70
      port 4141
    </server>
  </match>
  <source>
    type forward
    port 24224
  </source>
  <source>
    type http
    port 8888
  </source>
  <source>
    type debug_agent
    bind 127.0.0.1
    port 24230
  </source>
</ROOT>`
2015-11-24 23:51:48 -0500 [info]: listening fluent socket on 0.0.0.0:24224
2015-11-24 23:51:48 -0500 [info]: listening dRuby uri="druby://127.0.0.1:24230" object="Engine"
2015-11-24 23:52:49 -0500 [info]: Trying to send through '10.149.1.62'
2015-11-24 23:52:49 -0500 [error]: Got error for node '10.149.1.62:4141': Broken pipe, try reconnect
2015-11-24 23:52:49 -0500 [warn]: temporarily failed to flush the buffer. next_retry=2015-11-24 23:52:50 -0500 error_class="Thrift::TransportException" error="Could not connect to 10.149.1.62:4141: Connection refused - connect(2) for 10.149.1.62:4141" plugin_id="object:3fc906d8caac"
  2015-11-24 23:52:49 -0500 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/thrift-0.8.0/lib/thrift/transport/socket.rb:53:in `rescue in open'
  2015-11-24 23:52:49 -0500 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/thrift-0.8.0/lib/thrift/transport/socket.rb:36:in`open'
  2015-11-24 23:52:49 -0500 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/thrift-0.8.0/lib/thrift/transport/framed_transport.rb:37:in `open'
  2015-11-24 23:52:49 -0500 [warn]: /etc/td-agent/plugin/out_flume.rb:119:in`block in connect'
  2015-11-24 23:52:49 -0500 [warn]: /opt/td-agent/embedded/lib/ruby/2.1.0/timeout.rb:76:in `timeout'
  2015-11-24 23:52:49 -0500 [warn]: /etc/td-agent/plugin/out_flume.rb:114:in`connect'
  2015-11-24 23:52:49 -0500 [warn]: /etc/td-agent/plugin/out_flume.rb:61:in `rescue in block in write'
  2015-11-24 23:52:49 -0500 [warn]: /etc/td-agent/plugin/out_flume.rb:54:in`block in write'
  2015-11-24 23:52:49 -0500 [warn]: /etc/td-agent/plugin/out_flume.rb:53:in `each'
  2015-11-24 23:52:49 -0500 [warn]: /etc/td-agent/plugin/out_flume.rb:53:in`write'
  2015-11-24 23:52:49 -0500 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:325:in `write_chunk'
  2015-11-24 23:52:49 -0500 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/buffer.rb:304:in`pop'
  2015-11-24 23:52:49 -0500 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:321:in `try_flush'
  2015-11-24 23:52:49 -0500 [warn]: /opt/td-agent/embedded/lib/ruby/gems/2.1.0/gems/fluentd-0.12.12/lib/fluent/output.rb:140:in`run'
2015-11-24 23:52:50 -0500 [info]: Trying to send through '10.149.1.62'
2015-11-24 23:52:50 -0500 [error]: Got error for node '10.149.1.62:4141': Broken pipe, try reconnect
2015-11-24 23:52:50 -0500 [warn]: temporarily failed to flush the buffer. next_retry=2015-11-24 23:52:52 -0500 error_class="Thrift::TransportException" error="Could not connect to 10.149.1.62:4141: Connection refused - connect(2) for 10.149.1.62:4141" plugin_id="object:3fc906d8caac"
  2015-11-24 23:52:50 -0500 [warn]: suppressed same stacktrace
2015-11-24 23:52:52 -0500 [info]: Trying to send through '10.149.1.62'
2015-11-24 23:52:52 -0500 [error]: Got error for node '10.149.1.62:4141': Broken pipe, try reconnect
2015-11-24 23:52:52 -0500 [warn]: failed to flush the buffer. error_class="Thrift::TransportException" error="Could not connect to 10.149.1.62:4141: Connection refused - connect(2) for 10.149.1.62:4141" plugin_id="object:3fc906d8caac"
2015-11-24 23:52:52 -0500 [warn]: retry count exceededs limit.
  2015-11-24 23:52:52 -0500 [warn]: suppressed same stacktrace
2015-11-24 23:52:52 -0500 [error]: throwing away old logs.

**Comment by wd** [comment]
I think may be 'node.connect()' got an error again, there isn't a catch in connect. You can remove this line and try again, if it's working, then you can add a catch case in node.connect and make a pull request :D

**Comment by gluplu** [comment]
You are right, that seems to be it.
I will add the catch and make the pull request
Thank you!
